# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

#      - name: Setup Gem Files
#        run: |
#          bundle install --jobs 4 --retry 3

      - name: Setup ChefDK
        run: |
          cd /tmp
          wget https://packages.chef.io/files/stable/chefdk/4.11.0/ubuntu/18.04/chefdk_4.11.0-1_amd64.deb
          sudo apt install ./chefdk_4.11.0-1_amd64.deb
      - name: Setup Vagrant and VirtualBox
        run: |
          sudo wget https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_linux_amd64.zip
          sudo apt-get install unzip
          sudo unzip vagrant_2.2.10_linux_amd64.zip
          sudo mv vagrant /usr/bin/

      - name: Run Code Analysis using cookstyle
        run: |
          echo `pwd`
          echo "\n"
          chmod +x sca.sh
          ./sca.sh

      - name: Build and Bundle Cookbooks and dependencies
        run: |
          echo `pwd`
          echo "\n"
          chmod +x berks-vendor.sh
          echo `ls -l`
          ./berks-vendor.sh # Berks vendor cookbooks

#      - name: Run Chef InSpec Test
#        run: |
#          echo "Run Test Cases"
#          cd user_group
#          chef exec --chef-license 'accept-silent' kitchen verify 

      - name: Zip Artifacts
        run: |
          echo "Upload Artifacts to Github"
          tar -xvzf cookbooks.tar.gz cookbooks
